### ISSUE TITLE
Out of bound array access in m_win.f90

### ISSUE THREAD

**Issue by mogiso** [tktmyd/fwin#3]
I have encountered an out of bound array access in m_win.f90.
I use ifort version 19.1.0.166 on Linux.

At lines 410, when the variable n equals nb_buf, the index (n+1) is out of the array size of pb.
I suggest to expand the size of pb when n equals (nb_buf-1).

**Comment by mogiso** [comment]
This is an ad-hoc patch to read a win-formatted file whose number of  sec blocks is larger than NB_BUF_INIT:

--- ../fwin/src/m_win.f90       2021-03-02 15:27:45.805260800 +0900
+++ ./m_win.f90 2021-03-02 15:23:58.788538800 +0900
@@ -416,8 +416,14 @@
       end if
       
       !! expand buffer memory if necessary
-      if( n == nb_buf ) then
-        call expand_i( pb, nb_buf )
+      if( n == nb_buf - 1) then
+        nb_buf = size(pb); call expand_i( pb, nb_buf )
+        nb_buf = size(yr); call expand_i( yr, nb_buf )
+        nb_buf = size(mo); call expand_i( mo, nb_buf )
+        nb_buf = size(dy); call expand_i( dy, nb_buf )
+        nb_buf = size(hr); call expand_i( hr, nb_buf )
+        nb_buf = size(mi); call expand_i( mi, nb_buf )
+        nb_buf = size(sc); call expand_i( sc, nb_buf )
       end if
       
     end do

**Comment by tktmyd** [comment]
Thank you very much for your suggestion. Now the code includes your suggested code.
